/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Attack__factory } from "./Attack__factory";
export { InterfaceBankAccount__factory } from "./InterfaceBankAccount__factory";
