/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  InterfaceBankAccount,
  InterfaceBankAccountInterface,
} from "../../../contracts/Attack.sol/InterfaceBankAccount";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class InterfaceBankAccount__factory {
  static readonly abi = _abi;
  static createInterface(): InterfaceBankAccountInterface {
    return new utils.Interface(_abi) as InterfaceBankAccountInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InterfaceBankAccount {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InterfaceBankAccount;
  }
}
